spring:
  application:
    name: Backend
#  datasource:
#    url: jdbc:mysql://localhost:3306/assignment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 12345678
server:
  port: 8080
#by zhengkai.blog.csdn.net
#mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /Backend/v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /Backend/swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"

